apiVersion: apps/v1
kind: Deployment
metadata:
  name: wellbing
  labels:
    app: wellbing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wellbing
  template:
    metadata:
      labels:
        app: wellbing
    spec:
      containers:
        - name: wellbing
          image: username/wellbing:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5